language: java

# we don't use sudo to go faster
#sudo: true

env:
  matrix:
    - BUG="digits/070455301c2e18c7c89b850c2e86c311ac5fd223c84e723591012e163d60f11f5fd030343a444049a44940f8607d36c463f30556bf1efa98916d7417c2b4393c/000"

script: 
  - ./.travis-install.sh 
  - cd $BUG
  - mvn fr.inria.gforge.spirals:repair-maven-plugin:nopol

cache:
  directories:
  - IntroClassJava
  - nopol
  - maven-repair
